# .github/workflows/base.yml
name: Base Workflow
on:
  workflow_call:
    inputs:
      VERSION:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      ROLLBACK_ATTEMPTED:  # Define it as an input
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Print Current Directory
        run: pwd

      - name: List Files
        run: ls -la

      - name: Build Step
        run: echo "Building version ${{ inputs.VERSION }} for environment ${{ inputs.ENVIRONMENT }}"

      - name: Set rollback status
        run: |
          echo "ROLLBACK_ATTEMPTED=${{ inputs.ROLLBACK_ATTEMPTED }}" >> $GITHUB_ENV
          echo "ROLLBACK_ATTEMPTED=${{ inputs.ROLLBACK_ATTEMPTED }}" >> $GITHUB_OUTPUT
          echo "Rollback status set to ${{ inputs.ROLLBACK_ATTEMPTED }}"
