# base.yml
name: Base Workflow
on:
  workflow_call:
    inputs:
      VERSION:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      ROLLBACK_ATTEMPTED:
        required: false
        type: string
        default: 'false'  # Default to 'false' if not passed

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      rollback_attempted: ${{ steps.set-rollback-output.outputs.rollback_attempted }}  # Define the output

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Print Current Directory
        run: pwd

      - name: List Files
        run: ls -la

      - name: Build Step
        run: echo "Building version ${{ inputs.VERSION }} for environment ${{ inputs.ENVIRONMENT }}"

      - name: Set Rollback Attempted Output
        id: set-rollback-output
        run: |
          echo "rollback_attempted=${{ inputs.ROLLBACK_ATTEMPTED }}" >> $GITHUB_ENV  # Set the rollback_attempted value to environment
          echo "::set-output name=rollback_attempted::${{ inputs.ROLLBACK_ATTEMPTED }}"  # Set the output
